### PR TITLE
support cudnn

### PR DESCRIPTION
**Pull request by pint1022**
add cudnn support to coriander framework.

### CODE REVIEW

**Comment by hughperkins** [comment]
This just seems to squash my commits from the https://github.com/hughperkins/coriander/tree/adding-conv branch. The adding-conv branch is not yet working, so is not yet ready to merge to master. If you wish to work on the adding-conv branch, the correct approach is to create a branch from that branch eg:
```
git checkout adding-conv
git checkout -b adding-conv-pintmodification
# do things, make changes, use `git add` and `git commit` to commit them, then
# `git push` to push them to your github repo
```

=> closing this PR.

**Comment by pint1022** [comment]
It may look similar to your branch but it does the fix on cudnn. There are some changes in tf-coriander/stream_executor/cl and complete the build. But this part of fixes are necessary.

**Comment by hughperkins** [comment]
Ok. Please can you add the fix as a new commit, onto the adding-conv branch? When you create the PR, you'll put the base as 'adding-conv':

screen shot 2019-01-03 at 8 17 41 pm

Normally in the 'files changed' tab, you should see *only* your own changes.

**Comment by pint1022** [comment]
This is really the 1st time for me to commit the changes to open source repos. I just want to make cudnn work. I will retest the whole tf-coriander build under my account; then do the merge after it is successfully built from my branch. Will keep history of your work. You did an excellent work here.

**Comment by hughperkins** [comment]
Thank you Steven :)

**Pull request closed without merging**
