### PR TITLE
cudnn integration

### PR DESCRIPTION
**Pull request by pint1022**
Enable conv; fixed issues in instruction map and clwriter. 
only enable one algorithm (GEMM).
doesn't fix cltimer.

### CODE REVIEW

**Comment by pint1022** [comment]
I have added  and commited 15 files including CLwriter.cpp. Why are there 6-files marked as changed?

**Comment by hughperkins** [comment]
I'm not sure. What it looks like you're doing is merging my conv branch
onto master. Whether that is what you intend to do is unclear :)

**Comment by pint1022** [comment]
I am not clear the process here. Do I have to create a branch? if no, I don't have problem to check into your branch. Right now, I just worked on the local copy of the master.

**Comment by hughperkins** [comment]
I'm not sure what is your goal? The branch I created is a branch because it
doesn't really work yet. If you have a way of fixing that branch, I think
the sequence would be to pr onto the branch, then once it is working, we
can merge to master.

**Comment by pint1022** [comment]
I created another pull-request from my branch to replace this one. So I closed this one. Please take a look at the other pull-request to merge into the master.

**Pull request closed without merging**
